// @curio/tokens — Style Dictionary build.
//
// Single source for all three Curio products (pokemon-tool app, cardops-website, CurioCapture iOS).
// Source: the DTCG brand tokens (src/tokens/curio-brand.tokens.json, vendored from brand/v1.0.0) +
// the package-local design-system overrides (radius scale, dark-semantic extensions, independent
// status scale, type). Outputs, dark-only:
//   • dist/curio-brand.css            (Tailwind v4 @theme + :root — same format for app + website)
//   • dist/CurioTokens.swift           (reference copy)
//   • swift/Sources/CurioTokens/CurioTokens.swift  (the actual SwiftPM module source)
//
// A WCAG contrast validator runs after the build and FAILS the build if any status pairing drops
// below AA 4.5.
//
// Consuming repos install this package pinned to a git tag (github:<org>/curio-tokens#vX.Y.Z) and
// import dist/curio-brand.css directly (no hand-copying) or, for iOS, add this repo as a SwiftPM
// dependency and `import CurioTokens`.

import StyleDictionary from "style-dictionary";
import { cleanName, themeName, themeVar, isIosFont, isColor, isRadius, isSpacing, isFont,
         isTypeSize, isLeading, isWeight, scalesWithUserFont, isDuration, isEasing } from "./lib-names.mjs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Value coercion helpers (DTCG → platform value) ──────────────────────────

const to255 = (c) => Math.round(c * 255);
const hex2 = (n) => n.toString(16).padStart(2, "0");

/** DTCG color object | hex/rgba string → CSS colour string (#hex or rgba()). */
function colorToCss(value) {
  if (typeof value === "string") return value; // already hex / rgba
  if (value && Array.isArray(value.components)) {
    const [r, g, b] = value.components.map(to255);
    const a = value.alpha ?? 1;
    if (a >= 1) return `#${hex2(r)}${hex2(g)}${hex2(b)}`;
    return `rgba(${r}, ${g}, ${b}, ${Number(a.toFixed(3))})`;
  }
  return String(value);
}

const dimToCss = (v) => (typeof v === "object" && v ? `${v.value}${v.unit ?? "px"}` : `${v}px`);
const durToCss = (v) => (typeof v === "object" && v ? `${v.value}${v.unit ?? "ms"}` : `${v}ms`);
const bezierToCss = (v) => (Array.isArray(v) ? `cubic-bezier(${v.join(", ")})` : String(v));
const fontToCss = (v) => (Array.isArray(v) ? v.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(", ") : String(v));

// ── Clean CSS var / Swift names from token paths ────────────────────────────

// ── Transforms ──────────────────────────────────────────────────────────────
StyleDictionary.registerTransform({
  name: "curio/name", type: "name",
  transform: (token) => cleanName(token.path),
});
StyleDictionary.registerTransform({
  name: "curio/value", type: "value", transitive: true,
  transform: (token) => {
    const t = token.$type ?? token.type;
    const v = token.$value ?? token.value;
    switch (t) {
      case "color":       return colorToCss(v);
      case "dimension":   return dimToCss(v);
      case "duration":    return durToCss(v);
      case "cubicBezier": return bezierToCss(v);
      case "fontFamily":  return fontToCss(v);
      default:            return typeof v === "object" ? JSON.stringify(v) : String(v);
    }
  },
});

const TRANSFORMS = ["curio/name", "curio/value"];

// SD v4 DTCG mode keeps the (transformed) value on `$value`; fall back to `value` for safety.
const tv = (t) => t.$value ?? t.value;

// ── Formats ─────────────────────────────────────────────────────────────────
const header = "/* Curio brand tokens — GENERATED by @curio/tokens (Style Dictionary). Do not edit by hand. */\n/* Source: this package's src/tokens. Run: npm run build */\n";

StyleDictionary.registerFormat({
  name: "curio/css-theme",
  format: ({ dictionary }) => {
    const all = dictionary.allTokens.filter((t) => !isIosFont(t));
    // A type size emits a paired `--text-<n>--line-height` so `text-curio-body` sets BOTH size and
    // leading in one class. Without it every call site picks a leading, which is how the app ended
    // up inheriting line-height 1.5 everywhere and why TYPE-MIGRATION had to scope leading out.
    const leadingFor = (t) => all.find((x) => isLeading(x) && x.path[1] === t.path[1]);
    const theme = all.filter(themeVar).flatMap((t) => {
      const line = `  ${themeName(t)}: ${tv(t)};`;
      if (!isTypeSize(t)) return [line];
      const l = leadingFor(t);
      return l ? [line, `  ${themeName(t)}--line-height: ${tv(l)};`] : [line];
    }).join("\n");
    // The type scale is emitted TWICE, and deliberately. `--text-curio-*` exists to generate
    // Tailwind utilities and is web-only by construction; `--curio-type-*` is the name CONVENTIONS,
    // every component spec and both mobile lanes already cite, and it is the cross-platform one.
    // Both come from the same source token, so they cannot drift.
    const alsoRoot = (t) => isTypeSize(t) || isLeading(t) || isWeight(t) || isDuration(t) || isEasing(t);
    const root = all.filter((t) => !themeVar(t) || alsoRoot(t))
      .map((t) => `  --${cleanName(t.path)}: ${tv(t)};`).join("\n");
    return `${header}\n@theme {\n${theme}\n}\n\n:root {\n${root}\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: "curio/swift",
  format: ({ dictionary }) => {
    const swiftName = (path) => {
      const camel = cleanName(path).replace(/^curio-/, "").replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
      return camel.replace(/[^a-zA-Z0-9]/g, "");
    };
    const colors = [], dims = [], spacings = [], durs = [], others = [], weights = [];
    for (const t of dictionary.allTokens) {
      const type = t.$type ?? t.type;
      const name = swiftName(t.path);
      if (type === "color") {
        const c = String(tv(t));
        const m = c.match(/^#([0-9a-fA-F]{6})$/);
        if (m) {
          const r = parseInt(m[1].slice(0, 2), 16) / 255, g = parseInt(m[1].slice(2, 4), 16) / 255, b = parseInt(m[1].slice(4, 6), 16) / 255;
          colors.push(`    public static let ${name} = Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)})`);
        } else {
          const rm = c.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/);
          if (rm) colors.push(`    public static let ${name} = Color(red: ${(rm[1] / 255).toFixed(4)}, green: ${(rm[2] / 255).toFixed(4)}, blue: ${(rm[3] / 255).toFixed(4)}, opacity: ${rm[4] ?? "1"})`);
        }
      } else if (type === "dimension" && t.path[0] === "spacing") {
        spacings.push(`    public static let ${name}: CGFloat = ${parseFloat(tv(t))}`);
      } else if (type === "dimension") {
        dims.push(`    public static let ${name}: CGFloat = ${parseFloat(tv(t))}`);
      } else if (type === "duration") {
        durs.push(`    public static let ${name}: TimeInterval = ${parseFloat(tv(t)) / 1000}`);
      } else if (type === "fontFamily") {
        // font.display/product/evidence (CSS family-name stacks, e.g. "Plus Jakarta Sans") are
        // deliberately NOT emitted here. A CSS family name is not a PostScript name — passing one
        // to SwiftUI's Font.custom(name:) silently fails and falls back to system San Francisco,
        // no error. The iOS-only PostScript-name tokens below (font-ios.*) are the real fix; see
        // type-ios.json. brand.type.* (brandType*) is left alone — unused for Font.custom today,
        // out of scope for this pass.
        if (t.path[0] === "font" && ["display", "product", "evidence"].includes(t.path[1])) continue;
        others.push(`    public static let ${name} = ${JSON.stringify(String(tv(t)).split(",")[0].replace(/"/g, "").trim())}`);
      } else if (isWeight(t)) {
        // SwiftUI's Font.Weight has no public numeric initialiser, so the numeric value is what
        // crosses the boundary and the call site maps it. Emitted as Int rather than a named
        // Font.Weight so the four names stay one decision in src/tokens, not four here.
        weights.push(`    public static let ${name}: Int = ${parseInt(tv(t), 10)}`);
      } else if (isIosFont(t)) {
        // Real PostScript names, verified against the bundled font files' own name tables (see
        // type-ios.json's $description) — safe to use directly with Font.custom(name:).
        others.push(`    public static let ${name} = ${JSON.stringify(String(tv(t)))}`);
      }
    }
    return `// Curio brand tokens — GENERATED by @curio/tokens (Style Dictionary). Do not edit by hand.\n// Run: npm run build\nimport SwiftUI\n\npublic enum CurioTokens {\n  public enum Colors {\n${colors.join("\n")}\n  }\n  public enum Radius {\n${dims.join("\n")}\n  }\n  public enum Spacing {\n${spacings.join("\n")}\n  }\n  public enum Duration {\n${durs.join("\n")}\n  }\n  public enum Fonts {\n${others.join("\n")}\n  }\n  public enum Weight {\n${weights.join("\n")}\n  }\n}\n`;
  },
});

// ── Compose (Android) ───────────────────────────────────────────────────────
// Emits raw values (packed ARGB Long for color, Float for dp, Long milliseconds for duration)
// rather than androidx.compose.ui.graphics.Color/Dp directly — keeps this a plain Kotlin/JVM
// module with zero Compose/Android-SDK dependency to BUILD (mirrors @curio/contracts' Kotlin
// target: JitPack needs only a JDK). The consumer, whose app already depends on Compose, wraps
// at the call site: `Color(CurioTokens.Colors.x)`, `CurioTokens.Radius.x.dp`. Same posture as the
// Swift format's font handling below: Android has no PostScript-name equivalent to emit yet (font
// FILES aren't bundled for Android the way Sources/CurioTokens/Fonts/*.ttf are for iOS — a real
// gap, flagged, not silently worked around), so the Fonts section stays empty until that lands.
function colorToArgbLong(css) {
  const hex = css.match(/^#([0-9a-fA-F]{6})$/);
  const hex2 = (n) => n.toString(16).padStart(2, "0").toUpperCase();
  if (hex) return `0xFF${hex[1].toUpperCase()}`;
  const rgba = css.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/);
  if (rgba) {
    const a = rgba[4] !== undefined ? Math.round(parseFloat(rgba[4]) * 255) : 255;
    return `0x${hex2(a)}${hex2(+rgba[1])}${hex2(+rgba[2])}${hex2(+rgba[3])}`;
  }
  return null;
}

StyleDictionary.registerFormat({
  name: "curio/compose",
  format: ({ dictionary }) => {
    const composeName = (path) => {
      const camel = cleanName(path).replace(/^curio-/, "").replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
      return camel.replace(/[^a-zA-Z0-9]/g, "");
    };
    const colors = [], dims = [], spacings = [], durs = [], weights = [];
    for (const t of dictionary.allTokens) {
      const type = t.$type ?? t.type;
      const name = composeName(t.path);
      if (type === "color") {
        const argb = colorToArgbLong(String(tv(t)));
        if (argb) colors.push(`    public val ${name}: Long = ${argb}L`);
      } else if (type === "dimension" && t.path[0] === "spacing") {
        spacings.push(`    public val ${name}: Float = ${parseFloat(tv(t))}f`);
      } else if (type === "dimension") {
        dims.push(`    public val ${name}: Float = ${parseFloat(tv(t))}f`);
      } else if (type === "duration") {
        durs.push(`    public val ${name}: Long = ${Math.round(parseFloat(tv(t)))}L`);
      } else if (isWeight(t)) {
        // Compose's FontWeight(int) takes exactly this. Int, not Float — a weight is an enumeration
        // of nine defined values, not a measurement.
        weights.push(`    public val ${name}: Int = ${parseInt(tv(t), 10)}`);
      }
      // fontFamily / font-ios: intentionally not emitted — see header comment above.
    }
    return `// Curio brand tokens — GENERATED by @curio/tokens (Style Dictionary). Do not edit by hand.
// Run: npm run build
//
// Values are raw (Long ARGB / Float dp / Long ms), not androidx.compose.ui types — this keeps the
// module dependency-free to build. Wrap at the call site:
//   Color(CurioTokens.Colors.surfaceBase)
//   CurioTokens.Radius.radiusMd.dp
//   tween<Float>(durationMillis = CurioTokens.Duration.durationStandard.toInt())
package com.curio.tokens

public object CurioTokens {
  public object Colors {
${colors.join("\n")}
  }
  public object Radius {
${dims.join("\n")}
  }
  public object Spacing {
${spacings.join("\n")}
  }
  public object Duration {
${durs.join("\n")}
  }
  public object Weight {
${weights.join("\n")}
  }
}
`;
  },
});

// ── Android XML resources (View/XML-layout consumers) ───────────────────────
// Standard res/values/{colors,dimens}.xml — a secondary, lower-fidelity output for a consumer not
// using Compose. Unlike the Kotlin/JitPack target above, there is no "pin a git dependency and get
// these merged automatically" mechanism for bare resource XML without this becoming a real
// com.android.library AAR (which would need the Android SDK to build — out of scope for a
// dependency-free JVM module) — so this is generated, committed output the Android app copies
// into its own res/values/ at each version bump, same posture as how a web consumer references
// dist/curio-brand.css directly rather than it being a binary dependency.
// Android resource names must be valid identifiers (Android generates an R.color.<name>/
// R.dimen.<name> field from this exact string) — underscores only, no hyphens, unlike every
// other output format's dash-separated `curio-x-y` naming.
const androidResName = (path) => cleanName(path).replace(/-/g, "_");

StyleDictionary.registerFormat({
  name: "curio/android-colors-xml",
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens
      .filter((t) => (t.$type ?? t.type) === "color")
      .map((t) => {
        const argb = colorToArgbLong(String(tv(t)));
        return argb ? `    <color name="${androidResName(t.path)}">#${argb.slice(2)}</color>` : null;
      })
      .filter(Boolean);
    return `<?xml version="1.0" encoding="utf-8"?>\n<!-- Curio brand tokens — GENERATED by @curio/tokens (Style Dictionary). Do not edit by hand. -->\n<resources>\n${lines.join("\n")}\n</resources>\n`;
  },
});

StyleDictionary.registerFormat({
  name: "curio/android-dimens-xml",
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens
      .filter((t) => (t.$type ?? t.type) === "dimension")
      .map((t) => `    <dimen name="${androidResName(t.path)}">${parseFloat(tv(t))}${scalesWithUserFont(t) ? "sp" : "dp"}</dimen>`);
    return `<?xml version="1.0" encoding="utf-8"?>\n<!-- Curio brand tokens — GENERATED by @curio/tokens (Style Dictionary). Do not edit by hand. -->\n<resources>\n${lines.join("\n")}\n</resources>\n`;
  },
});

// ── Build ────────────────────────────────────────────────────────────────────
const source = [resolve(__dirname, "src/tokens/*.json")];

const DIST = resolve(__dirname, "dist") + "/";
const SWIFT_SOURCES = resolve(__dirname, "Sources/CurioTokens") + "/";
const KOTLIN_SOURCES = resolve(__dirname, "src/main/kotlin/com/curio/tokens") + "/";
const ANDROID_RES = resolve(__dirname, "dist/android/values") + "/";

const sd = new StyleDictionary({
  source,
  usesDtcg: true,
  log: { verbosity: "silent", warnings: "disabled" },
  platforms: {
    css: {
      transforms: TRANSFORMS, buildPath: DIST,
      files: [{ destination: "curio-brand.css", format: "curio/css-theme" }],
    },
    "swift-dist": {
      transforms: TRANSFORMS, buildPath: DIST,
      files: [{ destination: "CurioTokens.swift", format: "curio/swift" }],
    },
    "swift-package": {
      transforms: TRANSFORMS, buildPath: SWIFT_SOURCES,
      files: [{ destination: "CurioTokens.swift", format: "curio/swift" }],
    },
    "compose-dist": {
      transforms: TRANSFORMS, buildPath: DIST,
      files: [{ destination: "CurioTokens.kt", format: "curio/compose" }],
    },
    "compose-package": {
      transforms: TRANSFORMS, buildPath: KOTLIN_SOURCES,
      files: [{ destination: "CurioTokens.kt", format: "curio/compose" }],
    },
    "android-xml": {
      transforms: TRANSFORMS, buildPath: ANDROID_RES,
      files: [
        { destination: "colors.xml", format: "curio/android-colors-xml" },
        { destination: "dimens.xml", format: "curio/android-dimens-xml" },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log("✓ Tokens built → dist/curio-brand.css, dist/CurioTokens.swift, Sources/CurioTokens/CurioTokens.swift, src/main/kotlin/com/curio/tokens/CurioTokens.kt, dist/android/values/{colors,dimens}.xml");

// ── WCAG contrast validation (AA gate) ───────────────────────────────────────
//
// MUTATION-CHECKED 2026-09-02: red when a status colour is added to the palette and to no check —
// verified with a NOVEL hex and, since coverage is keyed by token name rather than value, also with
// a hex that already appears in another check. The value-keyed version passed that second probe,
// which is how `status-product` needs-decision and sold would have entered the palette unchecked.
//
// BLIND SPOTS — what a green run of this gate does NOT establish (ADR 0024, 2026-09-02):
//   1. Anything outside status/accent/focus. Surfaces, text, lines and the brand ramp are in no
//      check and the coverage guard does not require them to be.
//   2. That a listed pairing is the pairing the product actually draws. The lists are hand-written:
//      a colour is measured where the list says, not where it is rendered.
//   3. Type size. AA 4.5 is assumed for every entry; a genuinely large/semibold label needs only
//      3.0, and this gate takes no size input, so it is strict in a way it cannot justify per-entry.
//   4. The pill alphas below are a SECOND COPY of a design decision that lives in
//      canon/design/components/CONVENTIONS.md. There is no opacity token for them, so if the design
//      changes one this gate keeps measuring the old surface and stays green.
//   5. uiChecks is REPORT-ONLY. A graphical element below 3.0 prints a bullet and does not fail
//      the build. Only aaChecks and the coverage guard can turn this red.
// Validate the ACTUAL generated CSS (what every consumer imports), not an intermediate.
const { readFileSync } = await import("node:fs");
const css = readFileSync(`${DIST}curio-brand.css`, "utf8");
const val = {};
for (const m of css.matchAll(/--(?:color-|radius-|font-)?(curio-[a-z0-9-]+)\s*:\s*([^;]+);/g)) {
  val[m[1]] = m[2].trim();
}

function parseRGB(c) {
  const h = c.match(/^#([0-9a-fA-F]{6})$/);
  if (h) return [0, 2, 4].map((i) => parseInt(h[1].slice(i, i + 2), 16));
  const r = c.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/);
  if (r) return [+r[1], +r[2], +r[3], r[4] === undefined ? 1 : +r[4]];
  return null;
}
function composite(fg, bg) {
  if (fg.length < 4 || fg[3] >= 1) return fg.slice(0, 3);
  const a = fg[3];
  return [0, 1, 2].map((i) => Math.round(fg[i] * a + bg[i] * (1 - a)));
}
function lum([r, g, b]) {
  const f = (v) => { v /= 255; return v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4; };
  return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
}
function ratio(fgc, bgc) {
  const bg = parseRGB(bgc).slice(0, 3);
  const fg = composite(parseRGB(fgc), bg);
  const [a, b] = [lum(fg), lum(bg)].sort((x, y) => y - x);
  return (a + 0.05) / (b + 0.05);
}

const base = "curio-surface-base", raised = "curio-surface-raised";

// ── The tinted pill ──────────────────────────────────────────────────────────
// A status LABEL does not sit on the page background. It sits on a pill filled with its own colour
// at low alpha, over base or raised — so the surface it is read against is lighter than `base` and
// the ratio is WORSE than an on-dark/base check reports. Checking only against base measures a
// case the product does not render.
//
// The alphas are design decisions and currently live in canon/design (CONVENTIONS §1) as well as
// here. That duplication is a real gap: there is no opacity token for them, so this is a second
// copy that can drift. Recorded rather than hidden — the fix is a token, and it is not this change.
const PILL_ALPHA = { "low-confidence": 0.14, ready: 0.14, listed: 0.16, "needs-decision": 0.15 };

// A check side is either a TOKEN NAME (a string that exists in `val`) or a computed colour, which
// is written `{ computed: <css>, from: <label> }`. The distinction is what makes coverage
// meaningful: only token names count as covered, and a computed pill surface is not a token.
const T = (name) => name;
const pillOf = (tokenName, alpha, bgName) => {
  const bg = parseRGB(val[bgName]).slice(0, 3);
  const fg = parseRGB(val[tokenName]).slice(0, 3);
  const c = composite([...fg, alpha], bg);
  return { computed: `rgb(${c[0]}, ${c[1]}, ${c[2]})`, from: `${tokenName} @ ${alpha} over ${bgName}` };
};
const resolve_ = (side) => (typeof side === "string" ? val[side] : side.computed);

// Hard AA gate (≥4.5): status pairings + primary text.
const aaChecks = [
  ["status success ink-on-fill", T("curio-status-success-ink"), T("curio-status-success-fill")],
  ["status warning ink-on-fill", T("curio-status-warning-ink"), T("curio-status-warning-fill")],
  ["status danger ink-on-fill",  T("curio-status-danger-ink"),  T("curio-status-danger-fill")],
  ["status success on-dark/base", T("curio-status-success-on-dark"), T(base)],
  ["status warning on-dark/base", T("curio-status-warning-on-dark"), T(base)],
  ["status danger on-dark/base",  T("curio-status-danger-on-dark"),  T(base)],
  ["text primary / base",         T("curio-text-primary"), T(base)],
  ["text primary / raised",       T("curio-text-primary"), T(raised)],
];
// Report-only (UI/graphical ≥3.0): accents + focus + secondary text.
const uiChecks = [
  ["accent ready / base",      T("curio-accent-ready"), T(base)],
  ["accent evidence / base",   T("curio-accent-evidence"), T(base)],
  ["accent completion / base", T("curio-accent-completion"), T(base)],
  ["focus ring / base",        T("curio-focus-ring"), T(base)],
  ["text secondary / base",    T("curio-text-secondary"), T(base)],
];

// The product statuses land as LABELS on their own tinted pill, so they are checked there — over
// `raised`, the worse of the two surfaces and therefore the one that decides.
for (const name of ["low-confidence", "ready", "listed", "needs-decision"]) {
  const t = `curio-status-product-${name}`;
  if (val[t]) aaChecks.push([`status-product ${name} on its pill`, T(t), pillOf(t, PILL_ALPHA[name], raised)]);
}
// `sold` is the one FILLED pill in the product: its text sits ON the colour rather than beside it,
// which is a different pairing from the on-dark check its hex would otherwise borrow coverage from.
if (val["curio-status-product-sold"] && val["curio-text-on-accent"]) {
  aaChecks.push(["status-product sold — text on FILLED pill",
    T("curio-text-on-accent"), T("curio-status-product-sold")]);
}

let failed = 0;
console.log("\nWCAG contrast (dark) — AA gate ≥4.5:");
for (const [label, fg, bg] of aaChecks) {
  const f = resolve_(fg), b = resolve_(bg);
  if (!f || !b) { console.log(`  ? ${label}: missing token`); failed++; continue; }
  const r = ratio(f, b);
  const ok = r >= 4.5;
  if (!ok) failed++;
  console.log(`  ${ok ? "✓" : "✗"} ${label.padEnd(42)} ${r.toFixed(2)}`);
}
console.log("UI/graphical (report, target ≥3.0):");
for (const [label, fg, bg] of uiChecks) {
  const f = resolve_(fg), b = resolve_(bg);
  if (!f || !b) { console.log(`  ? ${label}: missing token`); continue; }
  const r = ratio(f, b);
  console.log(`  ${r >= 3 ? "✓" : "•"} ${label.padEnd(42)} ${r.toFixed(2)}${r < 3 ? "  (use for large/semibold + paper label)" : ""}`);
}

// ── COVERAGE: every status/accent/focus token is IN a check, BY NAME ─────────
//
// Keyed by token NAME. It used to be keyed by VALUE, and that was a hole with a live case behind
// it: any new token whose hex already appeared in some check counted as covered. Two tokens in this
// very release — status-product needs-decision and sold, which alias the semantic warning and
// success values — entered the palette in NO check and the build stayed green.
//
// Verified by mutation, twice. A probe colour reusing an existing hex passed the value-keyed guard;
// one bit different, it failed. A first attempt at this fix still resolved names through values and
// passed the same probe — the hole reproduced in a new shape. Only names work.
//
// Same colour in a different ROLE is a different pairing, and `sold` is the proof: it is a filled
// pill, so its text sits on the colour. An alias is therefore checked in its own role, never
// inherited. That means more entries in the lists, which is what the lists are for.
const coveredNames = new Set(
  [...aaChecks, ...uiChecks].flatMap(([, fg, bg]) => [fg, bg]).filter((s) => typeof s === "string"));
const uncovered = Object.keys(val)
  .filter((n) => /^curio-(status|accent|focus)-/.test(n))
  .filter((n) => !coveredNames.has(n));

if (uncovered.length > 0) {
  console.error(`\n✗ ${uncovered.length} colour token(s) are in the palette but in NO contrast check:`);
  for (const n of uncovered) console.error(`    --color-${n}: ${val[n]}`);
  console.error("  Add each to aaChecks (text/ink, ≥4.5) or uiChecks (graphical, ≥3.0) in build.mjs.");
  console.error("  Which list is a real decision: 4.5 is for anything read as text, 3.0 for a dot,");
  console.error("  bar or icon. Putting a label colour in uiChecks passes a gate it should not.");
  console.error("  Aliasing an already-checked colour is NOT coverage — check it in its own role.");
  failed++;
}

if (failed > 0) {
  console.error(`\n✗ ${failed} AA contrast check(s) failed — fix the token values before shipping.`);
  process.exit(1);
}
console.log(`\n✓ All AA gate checks pass, and all ${Object.keys(val).filter((n) => /^curio-(status|accent|focus)-/.test(n)).length} status/accent/focus tokens are covered by one.`);
