// Curio brand tokens — GENERATED by @curio/tokens (Style Dictionary). Do not edit by hand.
// Run: npm run build
import SwiftUI

public enum CurioTokens {
  public enum Colors {
    public static let brandArchive950 = Color(red: 0.0431, green: 0.0510, blue: 0.0706)
    public static let brandMidnight900 = Color(red: 0.0902, green: 0.1020, blue: 0.1686)
    public static let brandPaper50 = Color(red: 0.9529, green: 0.9412, blue: 0.9098)
    public static let brandCurioLight400 = Color(red: 0.4745, green: 0.8784, blue: 0.7647)
    public static let brandCurioLight700 = Color(red: 0.0902, green: 0.4039, blue: 0.3373)
    public static let brandViolet400 = Color(red: 0.5098, green: 0.4627, blue: 0.9098)
    public static let brandViolet700 = Color(red: 0.2980, green: 0.2471, blue: 0.7176)
    public static let brandAmber400 = Color(red: 0.9059, green: 0.6588, blue: 0.3608)
    public static let brandAmber800 = Color(red: 0.4824, green: 0.2980, blue: 0.0745)
    public static let brandLineOnDark = Color(red: 0.9529, green: 0.9412, blue: 0.9098, opacity: 0.14)
    public static let brandLineOnLight = Color(red: 0.0431, green: 0.0510, blue: 0.0706, opacity: 0.13)
    public static let brandIndexAmberOnDark = Color(red: 0.9059, green: 0.6588, blue: 0.3608, opacity: 0.38)
    public static let surfaceBase = Color(red: 0.0431, green: 0.0510, blue: 0.0706)
    public static let surfaceRaised = Color(red: 0.0902, green: 0.1020, blue: 0.1686)
    public static let surfaceSunken = Color(red: 0.0275, green: 0.0353, blue: 0.0510)
    public static let surfaceOverlay = Color(red: 0.1216, green: 0.1412, blue: 0.2196)
    public static let surfaceInset = Color(red: 0.1490, green: 0.1686, blue: 0.2510)
    public static let textPrimary = Color(red: 0.9529, green: 0.9412, blue: 0.9098)
    public static let textSecondary = Color(red: 0.9529, green: 0.9412, blue: 0.9098, opacity: 0.72)
    public static let textMuted = Color(red: 0.9529, green: 0.9412, blue: 0.9098, opacity: 0.52)
    public static let textOnAccent = Color(red: 0.0431, green: 0.0510, blue: 0.0706)
    public static let accentReady = Color(red: 0.4745, green: 0.8784, blue: 0.7647)
    public static let accentEvidence = Color(red: 0.5098, green: 0.4627, blue: 0.9098)
    public static let accentCompletion = Color(red: 0.9059, green: 0.6588, blue: 0.3608)
    public static let lineQuiet = Color(red: 0.9529, green: 0.9412, blue: 0.9098, opacity: 0.14)
    public static let lineStrong = Color(red: 0.9529, green: 0.9412, blue: 0.9098, opacity: 0.24)
    public static let fallbackSurfaceBase = Color(red: 0.9529, green: 0.9412, blue: 0.9098)
    public static let fallbackTextPrimary = Color(red: 0.0431, green: 0.0510, blue: 0.0706)
    public static let fallbackAccentReadyText = Color(red: 0.0902, green: 0.4039, blue: 0.3373)
    public static let fallbackAccentEvidenceText = Color(red: 0.2980, green: 0.2471, blue: 0.7176)
    public static let fallbackAccentAttentionText = Color(red: 0.4824, green: 0.2980, blue: 0.0745)
    public static let focusRing = Color(red: 0.9059, green: 0.6588, blue: 0.3608)
    public static let statusSuccessFill = Color(red: 0.1686, green: 0.7137, blue: 0.4510)
    public static let statusSuccessInk = Color(red: 0.0431, green: 0.0510, blue: 0.0706)
    public static let statusSuccessOnDark = Color(red: 0.3098, green: 0.8157, blue: 0.5608)
    public static let statusWarningFill = Color(red: 0.8784, green: 0.6549, blue: 0.2275)
    public static let statusWarningInk = Color(red: 0.0431, green: 0.0510, blue: 0.0706)
    public static let statusWarningOnDark = Color(red: 0.9137, green: 0.7176, blue: 0.3569)
    public static let statusDangerFill = Color(red: 0.8980, green: 0.3255, blue: 0.2392)
    public static let statusDangerInk = Color(red: 0.0431, green: 0.0510, blue: 0.0706)
    public static let statusDangerOnDark = Color(red: 0.9412, green: 0.5020, blue: 0.4235)
  }
  public enum Radius {
    public static let brandRadiusSmall: CGFloat = 6
    public static let brandRadiusMedium: CGFloat = 10
    public static let brandRadiusLarge: CGFloat = 16
    public static let brandRadiusFeature: CGFloat = 24
    public static let borderHairline: CGFloat = 1
    public static let blurGlowSm: CGFloat = 24
    public static let blurGlowMd: CGFloat = 48
    public static let blurGlowLg: CGFloat = 72
    public static let radiusSm: CGFloat = 4
    public static let radiusMd: CGFloat = 8
    public static let radiusLg: CGFloat = 16
    public static let radiusFeature: CGFloat = 24
  }
  public enum Spacing {
    public static let spacingXs: CGFloat = 4
    public static let spacingSm: CGFloat = 8
    public static let spacingMd: CGFloat = 12
    public static let spacingLg: CGFloat = 16
    public static let spacingXl: CGFloat = 24
    public static let spacingXxl: CGFloat = 32
  }
  public enum Duration {
    public static let durationFast: TimeInterval = 0.12
    public static let durationStandard: TimeInterval = 0.2
    public static let durationReveal: TimeInterval = 0.4
    public static let durationAmbient: TimeInterval = 8
  }
  public enum Fonts {
    public static let brandTypeDisplay = "Plus Jakarta Sans"
    public static let brandTypeProduct = "Plus Jakarta Sans"
    public static let brandTypeEvidence = "IBM Plex Mono"
    public static let fontDisplay = "Plus Jakarta Sans"
    public static let fontProduct = "Plus Jakarta Sans"
    public static let fontEvidence = "IBM Plex Mono"
  }
}
