// Curio brand tokens — GENERATED by @curio/tokens (Style Dictionary). Do not edit by hand.
// Run: npm run build
//
// Values are raw (Long ARGB / Float dp / Long ms), not androidx.compose.ui types — this keeps the
// module dependency-free to build. Wrap at the call site:
//   Color(CurioTokens.Colors.surfaceBase)
//   CurioTokens.Radius.radiusMd.dp
//   tween<Float>(durationMillis = CurioTokens.Duration.durationStandard.toInt())
package com.curio.tokens

public object CurioTokens {
  public object Colors {
    public val brandArchive950: Long = 0xFF0B0D12L
    public val brandMidnight900: Long = 0xFF171A2BL
    public val brandPaper50: Long = 0xFFF3F0E8L
    public val brandCurioLight400: Long = 0xFF79E0C3L
    public val brandCurioLight700: Long = 0xFF176756L
    public val brandViolet400: Long = 0xFF8276E8L
    public val brandViolet700: Long = 0xFF4C3FB7L
    public val brandAmber400: Long = 0xFFE7A85CL
    public val brandAmber800: Long = 0xFF7B4C13L
    public val brandLineOnDark: Long = 0x24F3F0E8L
    public val brandLineOnLight: Long = 0x210B0D12L
    public val brandIndexAmberOnDark: Long = 0x61E7A85CL
    public val surfaceBase: Long = 0xFF0B0D12L
    public val surfaceRaised: Long = 0xFF171A2BL
    public val surfaceSunken: Long = 0xFF07090DL
    public val surfaceOverlay: Long = 0xFF1F2438L
    public val surfaceInset: Long = 0xFF262B40L
    public val textPrimary: Long = 0xFFF3F0E8L
    public val textSecondary: Long = 0xB8F3F0E8L
    public val textMuted: Long = 0x85F3F0E8L
    public val textOnAccent: Long = 0xFF0B0D12L
    public val accentReady: Long = 0xFF79E0C3L
    public val accentEvidence: Long = 0xFF8276E8L
    public val accentCompletion: Long = 0xFFE7A85CL
    public val lineQuiet: Long = 0x24F3F0E8L
    public val lineStrong: Long = 0x3DF3F0E8L
    public val fallbackSurfaceBase: Long = 0xFFF3F0E8L
    public val fallbackTextPrimary: Long = 0xFF0B0D12L
    public val fallbackAccentReadyText: Long = 0xFF176756L
    public val fallbackAccentEvidenceText: Long = 0xFF4C3FB7L
    public val fallbackAccentAttentionText: Long = 0xFF7B4C13L
    public val focusRing: Long = 0xFFE7A85CL
    public val statusSuccessFill: Long = 0xFF2BB673L
    public val statusSuccessInk: Long = 0xFF0B0D12L
    public val statusSuccessOnDark: Long = 0xFF4FD08FL
    public val statusWarningFill: Long = 0xFFE0A73AL
    public val statusWarningInk: Long = 0xFF0B0D12L
    public val statusWarningOnDark: Long = 0xFFE9B75BL
    public val statusDangerFill: Long = 0xFFE5533DL
    public val statusDangerInk: Long = 0xFF0B0D12L
    public val statusDangerOnDark: Long = 0xFFF0806CL
  }
  public object Radius {
    public val brandRadiusSmall: Float = 6f
    public val brandRadiusMedium: Float = 10f
    public val brandRadiusLarge: Float = 16f
    public val brandRadiusFeature: Float = 24f
    public val borderHairline: Float = 1f
    public val blurGlowSm: Float = 24f
    public val blurGlowMd: Float = 48f
    public val blurGlowLg: Float = 72f
    public val radiusXs: Float = 4f
    public val radiusSm: Float = 8f
    public val radiusMd: Float = 12f
    public val radiusLg: Float = 16f
    public val radiusFeature: Float = 24f
  }
  public object Spacing {
    public val spacingXs: Float = 4f
    public val spacingSm: Float = 8f
    public val spacingMd: Float = 12f
    public val spacingLg: Float = 16f
    public val spacingXl: Float = 24f
    public val spacingXxl: Float = 32f
  }
  public object Duration {
    public val durationFast: Long = 120L
    public val durationStandard: Long = 200L
    public val durationReveal: Long = 400L
    public val durationAmbient: Long = 8000L
  }
}
